spring:
  redis:
    host: 192.168.56.2
    port: 6379
    password:
    database: 0
#spring.redis.pool.max-active=8
#spring.redis.pool.max-wait=-1
#spring.redis.pool.max-idle=8
#spring.redis.pool.min-idle=0
#spring.redis.timeout=1000